# Generated by Django 5.0.7 on 2024-10-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuenteFinanciacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa_interes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('plazo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngresoProyectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='gasto',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='tipo_ingreso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('duracion', models.IntegerField(help_text='Duración en días')),
                ('fecha_inicio', models.DateField()),
                ('roi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fuentes_financiacion', models.ManyToManyField(related_name='proyectos', to='finanzas_app.fuentefinanciacion')),
                ('ingresos_proyectados', models.ManyToManyField(related_name='proyectos', to='finanzas_app.ingresoproyectado')),
            ],
        ),
    ]
