# Generated by Django 5.0.7 on 2024-10-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0002_fuentefinanciacion_ingresoproyectado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasto',
            old_name='monto',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='gasto',
            old_name='categoria',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='gasto',
            old_name='fecha',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='gasto',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='gasto',
            old_name='nota',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='gasto',
            old_name='metodo_pago',
            new_name='paymentMethod',
        ),
        migrations.RenameField(
            model_name='gasto',
            old_name='tipo',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='monto',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='categoria',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='fecha',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='nota',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='metodo_pago',
            new_name='paymentMethod',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='fuente',
        ),
        migrations.AlterField(
            model_name='gasto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
