# Generated by Django 5.0.7 on 2024-10-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0003_rename_monto_gasto_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
