# Generated by Django 5.0.7 on 2024-10-13 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0004_alter_gasto_date_alter_ingreso_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='fuentes_financiacion',
        ),
        migrations.DeleteModel(
            name='FuenteFinanciacion',
        ),
    ]
