# Generated by Django 5.0.7 on 2024-10-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0005_remove_proyecto_fuentes_financiacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoproyectado',
            name='monto',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
