# Generated by Django 5.0.7 on 2024-10-13 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0006_alter_ingresoproyectado_monto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_inicio',
        ),
    ]
