# Generated by Django 5.0.7 on 2024-10-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0007_remove_proyecto_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='payback',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='total_ingresos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
