# Generated by Django 5.1.3 on 2024-11-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0008_proyecto_payback_proyecto_total_ingresos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='usuario',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='usuario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
